### Retrieve all clients
GET http://localhost:3000/tasks

### Retrieve a client by ID
GET http://localhost:3000/tasks/1


### Delete client
DELETE http://localhost:3000/tasks/1


### Create task
POST http://localhost:3000/tasks
Content-Type: application/json

{
      "category": "todo",
      "title": "Todo 3 ",
      "content": "Test"
}

### Update client
PUT http://localhost:3000/tasks/2
Content-Type: application/json

{
      "category": "blocked",
      "title": "Todo 2",
      "content": " jojo"
}