### Retrieve all tasks
GET http://localhost:3000/tasks

### Retrieve a task by ID
GET http://localhost:3000/tasks/3


### Delete task
DELETE http://localhost:3000/tasks/5


### Create task
POST http://localhost:3000/tasks
Content-Type: application/json

{
      "state": "done",
      "title": "test5",
      "content": "Test",
}

### Update task
PUT http://localhost:3000/tasks/2
Content-Type: application/json

{
      "state": "blocked",
      "title": "Todo 2",
      "content": " jojo"
}